---
title: Wellspaces
timezone: Asia/Jakarta
collections:
  big-banner:
    title: Big Banner
    output: true
  jumbotron:
    title: Jumbotron
    output: true
  micro-banner:
    title: Mini Banner
    output: true
  nav:
    title: Nav
    output: true
  posts:
    title: Posts
    output: true
  product:
    title: Product
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: nav
  values:
    layout: products
    permalink: "/product/"
- scope:
    path: ''
    type: product
  values:
    layout: product
    image:
    - "/uploads/image-tampak-depan.jpg"
    - "/uploads/image-tampak-belakang.jpg"
    brand: SABNANI
    price: 100000
    saleprice: 0
    color:
    - AS IMAGE
    size:
    - FREE SIZE
    teamwearprice:
    - "(Harga amateur set, diisi hanya pada produk teamwear)"
    - "(Harga pro set, diisi hanya pada produk teamwear)"
    teamweardesc:
    - "<p>Sabnani Amateur Set Jersey sesuai dengan tim Sepakbola yang ingin mengejar
      impian untuk menjadi tim profesional.</p><p>minimum pemesanan untuk Sabnani
      Amateur Set Jersey adalah 15 pcs, termasuk logo Klub, flock / Polyflex, Sabnani
      Logo (pada baju dan celana), logo Sponsor , Nama Pemain, Nomor pemain (pada
      baju dan celana).</p> <p>Anda dapat memilih atau memadukan bahan dengan kualitas
      “ Comfort Fit “Sabnani dengan pilihan bahan: Dot Drifit, Drifit Heksagonal,
      Wafer Drifit, Mesh Drifit, Serena Super, Billabong, Benzema & Paving.</p>"
    - "<p>Sabnani Pro Set Jersey sangat sesuai dengan tim Sepakbola profesional, team
      anda akan dibantu tim profesioanl dari Sabnani dalam hal pemuatan foto da video
      profile team sepakbola mu.</p> <p>Minimum pemesanan untuk Sabnani Amateur Set
      Jersey adalah 25 pcs, termasuk logo Klub, flock / Polyflex, Sabnani Logo (pada
      baju dan celana), logo Sponsor , Nama Pemain, Nomor pemain (pada baju dan celana).</p>
      <p>Anda dapat memilih atau memadukan bahan dengan kualitas “ Comfort Fit “Sabnani
      dengan pilihan bahan: Dot Drifit, Drifit Heksagonal, Wafer Drifit, Mesh Drifit,
      Serena Super, Billabong, Benzema & Paving.</p>"
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
name: Wellspaces Co.
description: Freewarespaces, Office Space, Jakarta Best Co Working Space.
logo: 
igid: 
igtoken: 
wa: 628567685884
google_analytics: 
url: https://kemtol.github.io/wellspace
baseurl: https://kemtol.github.io/wellspace
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
