---
title: Wellspaces
timezone: Asia/Jakarta
collections:
  big-banner:
    title: Big Banner
    output: true
  company:
    title: Company
    output: true
  deals:
    title: Deals
    output: true
  gallery:
    title: Gallery
    output: true
  jumbotron:
    title: Jumbotron
    output: true
  mediacoverage:
    title: Media Coverage
    output: true
  members:
    title: Members
    output: true
  nav:
    title: Nav
    output: true
  posts:
    title: Posts
    output: true
  product:
    title: Product
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: nav
  values:
    layout: products
    permalink: "/product/"
    image:
    - "/uploads/bg-img.jpg"
- scope:
    path: ''
    type: gallery
  values:
    layout: default
    author: "@someone"
    image:
    - "/uploads/gallery-1.jpg"
- scope:
    path: ''
    type: mediacoverage
  values:
    image:
    - "/uploads/media-logo.jpg"
- scope:
    path: ''
    type: product
  values:
    layout: product
    image:
    - "/uploads/pic-1.jpg"
    - "/uploads/pic-2.jpg"
    price:
      privatemonth: 15000000
      privateyear: 150000000
      sharedmonth: 15000000
      sharedyear: 150000000
    seotags:
    - You can put SEO tags here separated by coma
    seodesc:
    - You can put SEO desc here
    address: Equity Tower, 18th floor, RT.5/RW.3, Senayan, Kby. Baru, Kota Jakarta
      Selatan, Daerah Khusus Ibukota Jakarta 12190.
    pricedesc: Curabitur condimentum ut tortor ut vulputate. Donec pellentesque lorem
      lorem, in dictum ipsum dignissim vel. Vivamus condimentum ligula laoreet nisi
      egestas eleifend. Aliquam in metus consectetur, efficitur mi in, consequat leo.
      Sed feugiat risus eget congue tincidunt. Fusce sit amet sapien eu nulla sagittis
      ornare. Duis erat felis, tempus a aliquam eget, molestie vulputate sem. Etiam
      euismod id mi egestas pretium. Proin gravida tellus a tristique faucibus. Phasellus
      at sagittis diam.
    featuresdesc: Curabitur condimentum ut tortor ut vulputate. Donec pellentesque
      lorem lorem, in dictum ipsum dignissim vel. Vivamus condimentum ligula laoreet
      nisi egestas eleifend. Aliquam in metus consectetur, efficitur mi in, consequat
      leo. Sed feugiat risus eget congue tincidunt. Fusce sit amet sapien eu nulla
      sagittis ornare. Duis erat felis, tempus a aliquam eget, molestie vulputate
      sem. Etiam euismod id mi egestas pretium. Proin gravida tellus a tristique faucibus.
      Phasellus at sagittis diam.
    featureslist:
    - 15 Private Office Rooms
    - 12 Persons Meeting Room
    - Cozy Lounge
    video: https://youtu.be/embed/MqvdZ7Fo_8Y
    mapcoordinate: <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15865.135203714744!2d106.8084354!3d-6.2262628!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xf830686a95e909cf!2sFreeware+%2F+workwell+Suites+Equity+18+Sudirman+Coworking+Space+%26+Serviced+Office+(wellspaces)!5e0!3m2!1sen!2sid!4v1553237547798"
      width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    photo:
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
    - "/uploads/workwell-suites-SCBD.jpg"
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
name: Wellspaces Co.
description: Freewarespaces, Office Space, Jakarta Best Co Working Space.
logo: img/core-img/logo.png
igid: 
igtoken: 
wa: 
google_analytics: 
url: https://wellspaces.CO
baseurl:
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
