---
title: Wellspaces
timezone: Asia/Jakarta
collections:
  big-banner:
    title: Big Banner
    output: true
  deals:
    title: Deals
    output: true
  gallery:
    title: Gallery
    output: true
  jumbotron:
    title: Jumbotron
    output: true
  members:
    title: Members
    output: true
  mediacoverage:
    title: Media Coverage
    output: true
  nav:
    title: Nav
    output: true
  posts:
    title: Posts
    output: true
  product:
    title: Product
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: nav
  values:
    layout: products
    permalink: "/product/"
    image:
    - "/uploads/bg-img.jpg"
- scope:
    path: ''
    type: mediacoverage
  values:
    image:
    - "/uploads/media-logo.jpg"    
- scope:
    path: ''
    type: product
  values:
    layout: product
    image:
    - "/uploads/pic-1.jpg"
    - "/uploads/pic-2.jpg"
    price: 100000
    seotags:
    - You can put SEO tags here separated by coma
    seodesc:
    - You can put SEO desc here
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
name: Wellspaces Co.
description: Freewarespaces, Office Space, Jakarta Best Co Working Space.
logo: img/core-img/logo.png
igid: 
igtoken: 
wa: 
google_analytics: 
url: https://kemtol.github.io/wellspace
baseurl: https://kemtol.github.io/wellspace
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
